### ISSUE TITLE
A little typo

### ISSUE THREAD

**Issue by breadadams** [microlinkhq/support#1]
Just noticed a _typo_ in the docs:

![image](https://user-images.githubusercontent.com/5795227/33451169-7a266e46-d60e-11e7-9ffa-321d25951fd8.png)

Should be _[...] can make response time slow_ 😄

**Comment by Kikobeats** [comment]
Thanks! 

Documentation has is own repository, so please if you found any typo and you want to fix it you can do it directly

https://github.com/microlinkhq/docs/blob/master/source/index.html.md

😄

**Comment by breadadams** [comment]
Np! Dang I missed the repo @Kikobeats - I shall do so 👌
