### ISSUE TITLE
Rest api does not tell if domain didn't exist

### ISSUE THREAD

**Issue by Salmela** [microlinkhq/support#28]
## Bug Report

**Current Behavior**

[Currently](https://api.microlink.io/?url=https%3A%2F%2Fwww.awfghtegugsg-NOT-EXISTS-TEST-wifwufwf.com) the api gives `status: "success"` field even if the whole domain does not exist. And there seems to be nothing to distinguish the nonexistent domain response from any other random web page response.

**Expected behavior/code**

I expected that the status field would not be success or that there would be some other way to detect that the page does not exists.

**Additional context/Screenshots**

Example use case with your free rest api: https://api.microlink.io/?url=https%3A%2F%2Fwww.awfghtegugsg-BAD-DOMAIN-wifwufwf.com

**Comment by Kikobeats** [comment]
Closing because it's basically the same than https://github.com/microlinkhq/open/issues/29
