### ISSUE TITLE
Images urls that were once being returned are now returning null

### ISSUE THREAD

**Issue by oznekenzo** [microlinkhq/support#30]
We implemented microlink in our platform about two weeks ago - image preview urls were properly being fetched when we released to production, now all links that were once returning image urls are now null - any idea what's going on?

**Comment by oznekenzo** [comment]
Just realized that theyre working in my local environment but not on production

**Comment by oznekenzo** [comment]
So is it some cors issue? Dont understand - codebase hasnt changed but this stopped working - did something change with microlink?

**Comment by Kikobeats** [comment]
It looks like a problem related to your backend since CORS is properly supported on microlink API.

I'm going to close this because you don't provide enough information for being reproducible.
