### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by CKGrafico** [microlinkhq/support#33]
## Feature Request

**Is your feature request related to a problem? Please describe.**
As happy microlink user could be really nice to have a thumbnail of the website (not only a featured image)

**Describe the solution you'd like**
On the JSON of the response receive a thumbnail link / base64

**Describe alternatives you've considered**
My alternative is to make the thumbnail by myself.

**Teachability, Documentation, Adoption, Migration Strategy**
Using the API, nothing just enjoy. Using components maybe sending a parameter?

**Comment by breadadams** [comment]
Hey @CKGrafico - is this related/similar to the screenshot API? https://microlink.io/screenshot/

**Comment by Kikobeats** [comment]
You can use [Microlink for Insights](https://microlink.io/insights), that gives you a full Lighthouse report with thumbnails taken over the site from zero to load time 🙂
