### ISSUE TITLE
Facebook Page sometimes returns "Login or Signup to view"

### ISSUE THREAD

**Issue by matthewmayer** [microlinkhq/support#34]
## Bug Report

**Current Behavior**

https://api.microlink.io/?url=https%3A%2F%2Fwww.facebook.com%2Febisuph
https://api.microlink.io/?url=https%3A%2F%2Fwww.facebook.com%2Febisuph%2F

the first link works as expected. the second link returns `"title": "Log In or Sign Up to View",` even though the content of the two URLs is identical in a browser (note trailing slash on 2nd)

**Expected behavior/code**

Both should return `"title": "Ebisu Sushi Bar and Restaurant",`

**Possible Solution**

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Kikobeats** [comment]
Thanks for reporting @matthewmayer 

It should be fixed and work as expected

https://api.microlink.io/?url=https%3A%2F%2Fwww.facebook.com%2Febisuph

🙂
