### ISSUE TITLE
Metascraper not fetching description from OG tags

### ISSUE THREAD

**Issue by oyeanuj** [microlinkhq/support#37]
### Prerequisites

- I'm using the last version.
- My node version is the same as declared as `package.json`.

### Subject of the issue

For this given url, Metascraper does not seem to be fetching the description from the OG tags: https://thewritelaunch.com/2020/07/criminal-water/

Describe your issue here.

### Steps to reproduce

https://api.microlink.io/?url=https://thewritelaunch.com/2020/07/criminal-water/

### Expected behaviour

It should pick up the OG description tag.

### Actual behaviour

The description seems to be a random div tag:
```html
<div class="x-text-content"><div class="x-text-content-text"><h1 class="x-text-content-text-primary">Sign up for The Write Launch newsletter</h1></div></div></div>
```

**Comment by Kikobeats** [comment]
Thanks for reporting @oyeanuj!

It should be fixed and work as expected

https://api.microlink.io/?url=https://thewritelaunch.com/2020/07/criminal-water/

🙂

**Comment by oyeanuj** [comment]
@Kikobeats Thanks for the quick response (and apologies that this was in the wrong repo!)

It still seems to be not working correctly but I imagine that is a cached response, so I'll try again tomorrow!
