### ISSUE TITLE
Instagram links redirect to login page

### ISSUE THREAD

**Issue by jl4386** [microlinkhq/support#38]
## Bug Report

**Current Behavior**

When fetching instagram video links, it returns the login page data. 
E.g. https://api.microlink.io/?url=https://www.instagram.com/p/CEop3FlHAEl/&video

**Expected behavior/code**

Should return data with video links

**Possible Solution**

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Kikobeats** [comment]
Hello!

You need a pro plan. It will handle Instagram and other popular sites smothless

More about that: https://microlink.io/docs/api/parameters/proxy

**Comment by arcavid** [comment]
I think scrapping on Instagram stopped working.. I have put apiKey on mql / node.js

![image](https://user-images.githubusercontent.com/54137057/138540634-39a14945-fdb6-4e34-9ad4-24d339069497.png)

**Comment by Kikobeats** [comment]
Thanks for notifying, it's back to normal 🙂

**Comment by elmasry** [comment]
@Kikobeats FYI this is still an issue for Pro accounts, it returns a timeout
