### ISSUE TITLE
Correct Title is missing in Metadata // 

### ISSUE THREAD

**Issue by daniel-dty** [microlinkhq/support#39]
## Bug Report

**Current Behavior**

https://pro.microlink.io/?url=https://techcrunch.com/2020/10/06/helsinki-rides-the-slush-wave-toward-a-booming-startup-future/

The correct Title is NOT scraped from the webseite. Just "Techcrunch" and NOT "Helsinki rides the Slush wave toward a booming startup future"

**Expected behavior/code**

{"status":"success","data":{"title":"Helsinki rides the Slush wave toward a booming startup future","description":"In September 2020, Helsinki’s Ci...(...)

**Possible Solution**

Compare with the Website Title and don't just return a part of the Domain like "techcrunch"

**Comment by Kikobeats** [comment]
Hmm, I'm trying to reproduce the problem; every request I tried is returning the right information.

<img width="1803" alt="Screen Shot 2020-10-09 at 14 10 51" src="https://user-images.githubusercontent.com/2096101/95581392-3e536b00-0a39-11eb-96a2-23ed8c33f54b.png">

Need to wait sometime to infer if this was a temporal techcrunch or actually is a microlink problem.

**Comment by daniel-dty** [comment]
From today on it started to work again. Maybe temporarily....

Kiko Beats <notifications@github.com> schrieb am Fr., 9. Okt. 2020, 14:13:

**Comment by Kikobeats** [comment]
@daniel-dty super!

let me close the issue for a while; we can re-open it again in the future 🙂
