### ISSUE TITLE
Color detection is broken for logos

### ISSUE THREAD

**Issue by spiffytech** [microlinkhq/support#44]
## Bug Report

**Current Behavior**

Maybe 2-3 days ago, Meta API color detection for logos stopped working. Every site I've checked either has no color properties returned, or has them returned as `null`.

Without the logo color, my app has to fall back to the detected color from the OpenGraph image, which usually makes no sense since they don't include the site's brand colors.

**Expected behavior/code**

Fetching metadata with palette enabled should return logo colors

**Additional context/Screenshots**

I filed #42 and #43 before realizing this issue appears to be universal, rather than plaguing specific sites, and that it's specifically about logo colors and not OG image colors.

![image](https://user-images.githubusercontent.com/77867/160252966-781d6245-fba3-4d6e-89a7-8fd845fadb70.png)

![image](https://user-images.githubusercontent.com/77867/160252980-0c555ac8-44a5-4a4d-ae23-332b763727ae.png)

![image](https://user-images.githubusercontent.com/77867/160252996-1b40f31c-832d-4253-a59c-217cb70c1c0f.png)

**Comment by Kikobeats** [comment]
Hello, and thanks for reporting.

I'm working in to fix this asap 🙂

**Comment by Kikobeats** [comment]
@spiffytech Hey, it should be fixed now:

- https://api.microlink.io/?url=https://www.youtube.com/channel/UCTPjZ7UC8NgcZI8UKzb3rLw&palette
- https://api.microlink.io/?url=https://news.ycombinator.com/item?id=30811648&palette

Note Hacker News logo is reporting detecting was done, but it is not possible to detect palette for `ico` format. We're working to add this support as well 🙂

**Comment by spiffytech** [comment]
Looks good! 

My app must have been falling back to HN's site colors, and that color detection is working again, too.

Thanks!

**Comment by Kikobeats** [comment]
Hello again @spiffytech

I'm super happy to share you can now detect colors for ICO/BMP images as well.

e.g., https://api.microlink.io/?url=https%3A%2F%2Fmicrolink.io%2Ffavicon.ico&palette.

In fact, in case you are interested, all the following formats are supported now:

```
avif
bmp
cur
dds
eps
gif
heic
heif
ico
jpg
mng
odd
png
ps
psd
raw
svg
tga
tiff
webp
```

This is a non exhaustive list, but enough big to be compatible with almost any image 🙂

**Comment by spiffytech** [comment]
Excellent, I'm glad to see that roll out! Color palette support was an important reason I picked Microlink.

**Comment by Kikobeats** [comment]
That's super great!

Please, feel free to ping me again if you find any trouble, I want to be confident this work as good as possible 🙂
