### ISSUE TITLE
Only Good website unable to get details

### ISSUE THREAD

**Issue by Vitruvia13** [microlinkhq/support#51]
## Bug Report

**Current Behavior**

A clear and concise description of the behavior.

No data coming through

**Expected behavior/code**

A clear and concise description of what you expected to happen (or code).

Return logo micro link

**Possible Solution**

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Vitruvia13** [comment]
www.onlygood.co.nz

**Comment by Kikobeats** [comment]
Hello, the website doesn't have a logo, or in other words, what logo do you expect from this website?
