### ISSUE TITLE
Microlink rejects URL as invalid

### ISSUE THREAD

**Issue by spiffytech** [microlinkhq/support#52]
## Bug Report

**Current Behavior**

Microlink rejects links like this as invalid. I think it's because of the period at the end of the [text highlight](https://stackoverflow.com/a/62162093/191438)?

AFAICT the URL is valid. Node's `new URL(...)` accepts it, and the browser resolves it.

[https://example.com/#:~:text=This%20domain%20is%20for%20use%20in%20illustrative%20examples%20in%20documents.%20You%20may%20use%20this%20domain%20in%20literature%20without%20prior%20coordination%20or%20asking%20for%20permission.](https://example.com/#:~:text=This%20domain%20is%20for%20use%20in%20illustrative%20examples%20in%20documents.%20You%20may%20use%20this%20domain%20in%20literature%20without%20prior%20coordination%20or%20asking%20for%20permission.)

Microlink returns HTTP 400:

```json
{
  "status": "fail",
  "data": {
    "url": "The URL `https://example.com/#:~:text=This%20domain%20is%20for%20use%20in%20illustrative%20examples%20in%20documents.%20You%20may%20use%20this%20domain%20in%20literature%20without%20prior%20coordination%20or%20asking%20for%20permission.` is not valid. Ensure it has protocol, hostname and is reachable."
  },
  "code": "EINVALURL",
  "more": "https://microlink.io/einvalurl",
  "report": "..."
  "message": "The request has been not processed. See the errors above to know why."
}
```

**Expected behavior/code**

As the URL appears to be valid, I expect it to be scraped

**Additional context/Screenshots**

This URL uses a browser feature that highlights text on the page based on the contents of the URL's anchor tag.

**Comment by Kikobeats** [comment]
Thanks for reporting. It's clearly a valid URL. It seems our URL validator is being too strict and it isn't considering this case.

Let me figure out if we can land text fragment support 👍

**Comment by Kikobeats** [comment]
@spiffytech I'm happy to report that this is now working:

https://api.microlink.io/?url=https://example.com/#:~:text=This%20domain%20is%20for%20use%20in%20illustrative%20examples%20in%20documents.%20You%20may%20use%20this%20domain%20in%20literature%20without%20prior%20coordination%20or%20asking%20for%20permission.

Thanks for reporting this, the service is now better thanks to you 🙂

**Comment by spiffytech** [comment]
I can confirm scraping these links no longer errors out! Thanks!
