### ISSUE TITLE
`backdrop-filter: blur()` issues in microlink screenshot (browserless)

### ISSUE THREAD

**Issue by EllyLoel** [microlinkhq/support#55]
### Current behavior

`backdrop-filter: blur()` issues in microlink screenshot (browserless).

![](https://api.microlink.io/?url=https%3A%2F%2Fwww.ellyloel.com%2Fog/blog/web-directions-developer-summit-24-view-transitions-in-the-real-world/&screenshot=true&meta=false&embed=screenshot.url&force=true)

### Expected behavior

No `backdrop-filter: blur()` issues.

![](https://github.com/user-attachments/assets/3a14f33a-6db8-494a-ab80-813a95642800)

### Possible Solution

Update Puppeteer version as this issue is resolved in newer Chromium versions (>129 I believe).

**Comment by Kikobeats** [comment]
Hello, can you provide a way to reproduce this? It could be using browserless code or Microlink API.

Asking because Microlink is already using v131 Chrome version.

**Comment by EllyLoel** [comment]
oh interesting! here's the microlink api link that i'm using:

https://api.microlink.io/?url=https%3A%2F%2Fwww.ellyloel.com%2Fog/blog/web-directions-developer-summit-24-view-transitions-in-the-real-world/&screenshot=true&meta=false&embed=screenshot.url

and here's the page that's having the issue:

https://www.ellyloel.com/og/blog/web-directions-developer-summit-24-view-transitions-in-the-real-world/

**Comment by Kikobeats** [comment]
I built a tiny site just to verify it works:

https://api.microlink.io/?url=https://kzmno2q6me5h78i1guod.lite.vusercontent.net/&screenshot&embed=screenshot.url&waitForTimeout=1500

So I think your website is producing a different output as you expected, but I don't think that means backdrop is not working

**Comment by EllyLoel** [comment]
If you look at the edges of the blured box you can see that the microlink API output has an issue that the browserless output doesn't.
## Microlink API output
![Blur issue](https://github.com/user-attachments/assets/b706978f-9a67-45a3-bfc5-8f61b24a3dcf)
## Browserless output
![Blur working](https://github.com/user-attachments/assets/3ae0bec2-6041-4315-a08e-ea90c57cd241)

**Comment by Kikobeats** [comment]
You're right; I believe that is kind of expected since headless browser running in a server is not supporting WebGL acceleration and that is making the effect more simple:

https://github.com/microlinkhq/browserless/blob/3f22a6f3d6bb9e486fd406a784bb10f47532f491/packages/screenshot/test/index.js#L47

**Comment by EllyLoel** [comment]
Ah yes! That's it, thanks for helping me figure this out. It looks like this is a [Chromium issue](https://issues.chromium.org/issues/40916020) as Firefox without hardware acceleration works fine.
